<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NOP6ZpX' shared service.

return $this->privates['.service_locator.NOP6ZpX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::addCaissier' => ['privates', '.service_locator.BLqAp1.', 'get_ServiceLocator_BLqAp1_Service.php', true],
    'App\\Controller\\PartenaireController::addCompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::addUserPartenaire' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::ajoutPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::bloquer' => ['privates', '.service_locator.Kudu2tG', 'get_ServiceLocator_Kudu2tGService.php', true],
    'App\\Controller\\PartenaireController::depotCompte' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\PartenaireController::listerPartenaire' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController::makeTransaction' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:addCaissier' => ['privates', '.service_locator.BLqAp1.', 'get_ServiceLocator_BLqAp1_Service.php', true],
    'App\\Controller\\PartenaireController:addCompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:addUserPartenaire' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:ajoutPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:bloquer' => ['privates', '.service_locator.Kudu2tG', 'get_ServiceLocator_Kudu2tGService.php', true],
    'App\\Controller\\PartenaireController:depotCompte' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\PartenaireController:listerPartenaire' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController:makeTransaction' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\PartenaireController::addCaissier' => '?',
    'App\\Controller\\PartenaireController::addCompte' => '?',
    'App\\Controller\\PartenaireController::addUserPartenaire' => '?',
    'App\\Controller\\PartenaireController::ajoutPartenaire' => '?',
    'App\\Controller\\PartenaireController::bloquer' => '?',
    'App\\Controller\\PartenaireController::depotCompte' => '?',
    'App\\Controller\\PartenaireController::listerPartenaire' => '?',
    'App\\Controller\\PartenaireController::makeTransaction' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\PartenaireController:addCaissier' => '?',
    'App\\Controller\\PartenaireController:addCompte' => '?',
    'App\\Controller\\PartenaireController:addUserPartenaire' => '?',
    'App\\Controller\\PartenaireController:ajoutPartenaire' => '?',
    'App\\Controller\\PartenaireController:bloquer' => '?',
    'App\\Controller\\PartenaireController:depotCompte' => '?',
    'App\\Controller\\PartenaireController:listerPartenaire' => '?',
    'App\\Controller\\PartenaireController:makeTransaction' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
