<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FaSoWXN' shared service.

return $this->privates['.service_locator.FaSoWXN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'transaction' => ['privates', '.errored..service_locator.FaSoWXN.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.FaSoWXN": it references class "App\\Entity\\Transaction" but no such service exists.'],
], [
    'entityManager' => '?',
    'serializer' => '?',
    'transaction' => 'App\\Entity\\Transaction',
]);
