<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84GxhHq\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84GxhHq/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container84GxhHq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container84GxhHq\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container84GxhHq\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '84GxhHq',
    'container.build_id' => '24c7f56a',
    'container.build_time' => 1565205613,
], __DIR__.\DIRECTORY_SEPARATOR.'Container84GxhHq');
