<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJm47rm5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJm47rm5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJm47rm5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJm47rm5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJm47rm5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Jm47rm5',
    'container.build_id' => 'f8366c5a',
    'container.build_time' => 1567620675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJm47rm5');
