<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIp8RKxe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIp8RKxe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIp8RKxe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIp8RKxe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIp8RKxe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ip8RKxe',
    'container.build_id' => 'ebfa07b0',
    'container.build_time' => 1572252733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIp8RKxe');
