<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXopOT6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXopOT6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAXopOT6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAXopOT6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAXopOT6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AXopOT6',
    'container.build_id' => 'a9232a87',
    'container.build_time' => 1566063196,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXopOT6');
